services:
    postgres-db:
        image: postgres
        volumes:
            - ./postgres:/data/postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: example
            PGDATA: /data/postgres
